SELECT A.ITEM_ID AS ITEM_ID, A.ITEM_NAME AS ITEM_NAME, A.RARITY AS RARITY
FROM ITEM_INFO AS A
    LEFT JOIN ITEM_TREE AS B
    ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE B.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC;