SELECT A.ID,
CASE 
    WHEN A.PER_RANK <= 0.25 THEN 'CRITICAL'
    WHEN A.PER_RANK <= 0.5 THEN 'HIGH'
    WHEN A.PER_RANK <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM (
    SELECT ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER_RANK
    FROM ECOLI_DATA
) AS A
ORDER BY A.ID ASC;