SELECT f.FLAVOR
FROM FIRST_HALF f
INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS "TOT_ORDER"
    FROM JULY
    GROUP BY FLAVOR
) j
ON f.FLAVOR = j.FLAVOR
ORDER BY f.TOTAL_ORDER + j.TOT_ORDER DESC
LIMIT 3;