SELECT B.USER_ID, B.NICKNAME, SUM(C.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS B
JOIN USED_GOODS_BOARD AS C
ON B.USER_ID = C.WRITER_ID
WHERE C.STATUS = 'DONE'
GROUP BY B.USER_ID, B.NICKNAME
HAVING SUM(C.PRICE) >= 700000 
ORDER BY TOTAL_SALES ASC;