SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
( # YEAR의 최대 대장균 크기 구하기
    SELECT MAX(SIZE_OF_COLONY)
    FROM ECOLI_DATA
    WHERE YEAR(DIFFERENTIATION_DATE) = YEAR
) - SIZE_OF_COLONY AS YEAR_DEV,
ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV