SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS SALES
INNER JOIN ICECREAM_INFO AS INFO
ON SALES.FLAVOR = INFO.FLAVOR
GROUP BY INFO.INGREDIENT_TYPE
ORDER BY SUM(TOTAL_ORDER) ASC