SELECT CONCAT('/home/grep/src/', BOARD.BOARD_ID, '/', FILE.FILE_ID, FILE.FILE_NAME, FILE.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS BOARD
JOIN ( 
    SELECT MAX(A.VIEWS) AS MAX_VAL
    FROM USED_GOODS_BOARD AS A
) B
ON BOARD.VIEWS = B.MAX_VAL
JOIN USED_GOODS_FILE AS FILE
ON BOARD.BOARD_ID = FILE.BOARD_ID
ORDER BY FILE.FILE_ID DESC;